# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18a9RSIjwcbt3epJ_seo_JOmeT7afpIAX
"""

from google.colab import userdata

api_key = userdata.get("AZURE_OPENAI_API_KEY")
print("Loaded key:", api_key[:6] + "..." if api_key else "Missing")

from google.colab import userdata
from openai import OpenAI

my_endpoint = "https://25april3.services.ai.azure.com/api/projects/proj-default"
my_agent = "25april3"
my_version = "2"

api_key = userdata.get("AZURE_OPENAI_API_KEY")

openai_client = OpenAI(
    base_url=f"{my_endpoint}/openai/v1",
    api_key=api_key
)

response = openai_client.responses.create(
    input=[{"role": "user", "content": "Tell me what you can help with."}],
    extra_body={
        "agent_reference": {
            "name": my_agent,
            "version": my_version,
            "type": "agent_reference"
        }
    },
)

print(response.output_text)

from google.colab import userdata
from openai import OpenAI

# Config
my_endpoint = "https://25april3.services.ai.azure.com/api/projects/proj-default"
my_agent = "25april3"
my_version = "2"

api_key = userdata.get("AZURE_OPENAI_API_KEY")

client = OpenAI(
    base_url=f"{my_endpoint}/openai/v1",
    api_key=api_key
)

# Dynamic input
user_query = input("Ask your question: ")

# API call
response = client.responses.create(
    input=[
        {
            "role": "user",
            "content": user_query
        }
    ],

    extra_body={
        "agent_reference": {
            "name":my_agent,
            "version": my_version,
            "type": "agent_reference"
        }
    },
)

print("\n🤖 Bot:", response.output_text)